/**
 * @file kerr_observer_test.cpp
 * @brief Falsification gates for physics/kerr_observer.h and the KerrTimeField
 *        that delegates to it: radii, clocks, and delays against a 50-digit
 *        mpmath referee; tetrad orthonormality against the textbook
 *        Boyer-Lindquist metric; photon constants against closed-form orbits
 *        and special relativity.
 *
 * The reference block between the clang-format markers is the verbatim output
 * of `$PYTHON scripts/gen_kerr_observer_reference.py` (mpmath 1.4.1,
 * mp.dps = 50), which evaluates the textbook (a, r) formulas and integrates the
 * delay by quadrature; regenerate and diff to audit it.
 */

#include <array>
#include <cfloat>
#include <cmath>
#include <cstddef>
#include <numbers>

#include <gtest/gtest.h>

#include "game/kerr_time_field.h"
#include "kerr.h"
#include "kerr_observer.h"

namespace {

namespace ko = physics::kerr_observer;
using ko::OrbitSense;

struct RadiiRow {
  double epsilon;
  double xIscoPro;
  double xIscoRetro;
  double xMbPro;
  double xMbRetro;
  double xPhPro;
  double xPhRetro;
};

struct PointRow {
  double epsilon;
  double x;
  double alpha;
  double omega;
  double varpi;
  double ratePro; ///< -1: no timelike prograde circular orbit.
  double omegaPro;
  double rateRetro; ///< -1: no timelike retrograde circular orbit.
  double omegaRetro;
};

struct DelayRow {
  double epsilon;
  double x1;
  double x2;
  double delayM;
};

// clang-format off
// Generated by $PYTHON scripts/gen_kerr_observer_reference.py (mpmath 1.4.1, mp.dps = 50).
constexpr std::array<RadiiRow, 8> K_RADII{{
    {.epsilon = 1.33e-14, .xIscoPro = 3.7611284825013188359e-5, .xIscoRetro = 7.9999999999999625937, .xMbPro = 2.3065126519341591779e-7, .xMbRetro = 4.8284271247461673931, .xPhPro = 1.8832596446878474102e-7, .xPhRetro = 2.9999999999999881778},
    {.epsilon = 1e-8, .xIscoPro = 3.4301953390679368806e-3, .xIscoRetro = 7.9999999718749999864, .xMbPro = 2.0001e-4, .xMbRetro = 4.8284271076751222769, .xPhPro = 1.6330376052415161665e-4, .xPhRetro = 2.9999999911111111029},
    {.epsilon = 1e-4, .xIscoPro = 7.852643464645700713e-2, .xIscoRetro = 7.9997187486376610135, .xMbPro = 2.01e-2, .xMbRetro = 4.8282564131841658686, .xPhPro = 1.6374270630470882591e-2, .xPhRetro = 2.9999111102880463338},
    {.epsilon = 0.002, .xIscoPro = 2.3697065517518429022e-1, .xIscoRetro = 7.994374454803568801, .xMbPro = 9.1442719099991587856e-2, .xMbRetro = 4.8250125574535391512, .xPhPro = 7.3909257679951701678e-2, .xPhRetro = 2.9982218928479460127},
    {.epsilon = 0.1, .xIscoPro = 1.3208830417618872468, .xIscoRetro = 7.717352279606489316, .xMbPro = 7.324555320336758664e-1, .xMbRetro = 4.6568097504180443536, .xPhPro = 5.5785462742338280309e-1, .xPhRetro = 2.910267939103036726},
    {.epsilon = 0.4, .xIscoPro = 2.8290694188131495542, .xIscoRetro = 6.8506861853065783143, .xMbPro = 1.6649110640673517328, .xMbRetro = 4.1298221281347034656, .xPhPro = 1.1889140197636331308, .xPhRetro = 2.6298496971319209483},
    {.epsilon = 1.0, .xIscoPro = 5.0, .xIscoRetro = 5.0, .xMbPro = 3.0, .xMbRetro = 3.0, .xPhPro = 2.0, .xPhRetro = 2.0},
    {.epsilon = 1.9, .xIscoPro = 1.3208830417618872468, .xIscoRetro = 7.717352279606489316, .xMbPro = 7.324555320336758664e-1, .xMbRetro = 4.6568097504180443536, .xPhPro = 5.5785462742338280309e-1, .xPhRetro = 2.910267939103036726},
}};
// A rate of -1 marks a sense with no timelike circular orbit at that radius.
constexpr std::array<PointRow, 8> K_POINTS{{
    {.epsilon = 1.33e-14, .x = 3.7611284825013188359e-5, .alpha = 1.880546559306311743e-5, .omega = 4.9998119453442356177e-1, .varpi = 2.0000000010609100082, .ratePro = 1.6285857804897317108e-5, .omegaPro = 4.9998589603343017509e-1, .rateRetro = -1.0, .omegaRetro = 0.0},
    {.epsilon = 0.1, .x = 5.0, .alpha = 8.179815713894085549e-1, .omega = 8.0906148867313915858e-3, .varpi = 6.0893349390553316812, .ratePro = 7.4344405871481958781e-1, .omegaPro = 6.4115146878103390442e-2, .rateRetro = 6.5451153007973629037e-1, .omegaRetro = -7.2479847840044001065e-2},
    {.epsilon = 0.1, .x = 7.0e-1, .alpha = 2.5391996310095110195e-1, .omega = 2.2756005056890012642e-1, .varpi = 2.1570677264449969595, .ratePro = 1.5480159967808213366e-1, .omegaPro = 3.2086980691418488008e-1, .rateRetro = -1.0, .omegaRetro = 0.0},
    {.epsilon = 0.1, .x = 1.9e+1, .alpha = 9.4869394695727728785e-1, .omega = 2.2449992641391300877e-4, .varpi = 2.0022262609405561385e+1, .ratePro = 9.2351204119250342844e-1, .omegaPro = 1.1068960619761699354e-2, .rateRetro = 9.2023464826813378357e-1, .omegaRetro = -1.1293983403318534484e-2},
    {.epsilon = 1.0, .x = 2.0, .alpha = 5.7735026918962576451e-1, .omega = 0.0, .varpi = 3.0, .ratePro = -1.0, .omegaPro = 0.0, .rateRetro = -1.0, .omegaRetro = 0.0}, // NOLINT(modernize-use-std-numbers) -- generated reference value
    {.epsilon = 1.0, .x = 5.0, .alpha = 8.1649658092772603273e-1, .omega = 0.0, .varpi = 6.0, .ratePro = 7.071067811865475244e-1, .omegaPro = 6.8041381743977169394e-2, .rateRetro = 7.071067811865475244e-1, .omegaRetro = -6.8041381743977169394e-2}, // NOLINT(modernize-use-std-numbers) -- generated reference value
    {.epsilon = 0.002, .x = 5.0e-1, .alpha = 2.3191164750530924223e-1, .omega = 2.9091909738123257e-1, .varpi = 2.1386933705731014243, .ratePro = 1.9056173891204197645e-1, .omegaPro = 3.5271909119955795371e-1, .rateRetro = -1.0, .omegaRetro = 0.0},
    {.epsilon = 1.9, .x = 9.0, .alpha = 8.9460655096881942211e-1, .omega = -1.7826724240383472646e-3, .varpi = 1.0048482472493048042e+1, .ratePro = 8.4593629853609765265e-1, .omegaPro = -3.0747682224285464546e-2, .rateRetro = 8.2541375464928158576e-1, .omegaRetro = 3.2549141406222833815e-2},
}};
constexpr std::array<DelayRow, 8> K_DELAYS{{
    {.epsilon = 0.1, .x1 = 7.0e-1, .x2 = 3.99e+2, .delayM = 4.1482361145577006912e+2},
    {.epsilon = 0.1, .x1 = 5.0, .x2 = 1.9e+1, .delayM = 1.6972841054704438523e+1},
    {.epsilon = 1.0, .x1 = 2.0, .x2 = 1.99e+2, .delayM = 2.0757653406138907047e+2},
    {.epsilon = 0.002, .x1 = 1.0e-1, .x2 = 9.9e+1, .delayM = 1.3675521082077710728e+2},
    {.epsilon = 1e-8, .x1 = 1.0e-2, .x2 = 4.9e+1, .delayM = 2.6595669959515530504e+2},
    {.epsilon = 1.33e-14, .x1 = 3.7611284825013188359e-5, .x2 = 9.0, .delayM = 5.320941180415867699e+4},
    {.epsilon = 1.33e-14, .x1 = 3.7611284825013188359e-5, .x2 = 3.99e+2, .delayM = 5.360721248752867818e+4},
    {.epsilon = 0.0, .x1 = 5.0e-1, .x2 = 1.0e+1, .delayM = 1.9291464547107981987e+1},
}};
// clang-format on

constexpr double K_CANON_EPSILON = 1.33e-14;
constexpr double K_SOLAR_MASS_G = 1.989e33;

void expectRelative(double actual, double expected, double tolerance, const char *what) {
  if (expected == 0.0) {
    EXPECT_NEAR(actual, 0.0, tolerance) << what;
    return;
  }
  EXPECT_NEAR(actual / expected, 1.0, tolerance)
      << what << " actual=" << actual << " expected=" << expected;
}

/** Textbook equatorial Boyer-Lindquist metric g_{mu nu} in (a, r), M = 1. */
std::array<ko::Vec4, 4> textbookMetric(double spin, double r) {
  const double delta = (r * r) - (2.0 * r) + (spin * spin);
  std::array<ko::Vec4, 4> g{};
  g.at(0).at(0) = -(1.0 - (2.0 / r));
  g.at(0).at(3) = -2.0 * spin / r;
  g.at(3).at(0) = g.at(0).at(3);
  g.at(3).at(3) = (r * r) + (spin * spin) + (2.0 * spin * spin / r);
  g.at(1).at(1) = r * r / delta;
  g.at(2).at(2) = r * r;
  return g;
}

double contract(const std::array<ko::Vec4, 4> &g, const ko::Vec4 &u, const ko::Vec4 &v) {
  double sum = 0.0;
  for (std::size_t mu = 0; mu < 4; ++mu) {
    for (std::size_t nu = 0; nu < 4; ++nu) {
      sum += g.at(mu).at(nu) * u.at(mu) * v.at(nu);
    }
  }
  return sum;
}

/** Largest |g(e_a, e_b) - eta_ab| over the tetrad's legs, textbook metric. */
double orthonormalityError(const ko::Tetrad &tetrad) {
  const auto g = textbookMetric(tetrad.frame.spin, tetrad.frame.r);
  double worst = 0.0;
  for (std::size_t a = 0; a < 4; ++a) {
    for (std::size_t b = 0; b < 4; ++b) {
      double eta = 0.0;
      if (a == b) {
        eta = a == 0 ? -1.0 : 1.0;
      }
      const double value = contract(g, ko::legComponents(tetrad, a), ko::legComponents(tetrad, b));
      worst = std::fmax(worst, std::fabs(value - eta));
    }
  }
  return worst;
}

/** BPT closed-form u^t and Omega for a circular orbit in (a, r), M = 1. */
struct TextbookOrbit {
  double timeComponent;
  double angularVelocity;
};

TextbookOrbit textbookOrbit(double spin, double r, double sense) {
  const double r32 = r * std::sqrt(r);
  const double radicand = r32 - (3.0 * std::sqrt(r)) + (2.0 * sense * spin);
  return {.timeComponent = (r32 + (sense * spin)) / (std::pow(r, 0.75) * std::sqrt(radicand)),
          .angularVelocity = sense / (r32 + (sense * spin))};
}

/** Direction `index` of a `count`-point Fibonacci lattice on the unit sphere:
 *  deterministic on every standard library and uniform to O(1/count). */
ko::Vec3 latticeDirection(int index, int count) {
  const double z = 1.0 - ((2.0 * (static_cast<double>(index) + 0.5)) / static_cast<double>(count));
  const double ring = std::sqrt(1.0 - (z * z));
  const double goldenAngle = std::numbers::pi * (3.0 - std::sqrt(5.0));
  const double phi = goldenAngle * static_cast<double>(index);
  return {ring * std::cos(phi), z, ring * std::sin(phi)};
}

} // namespace

// Falsifier: any ISCO, marginally bound, or photon-orbit offset from the
// deficit algebra differing from the BPT closed form evaluated at 50 digits by
// more than 1e-12 relative, for either sense, from eps = 1.33e-14 to a = -0.9
// (senses relative to the hole's rotation, so a = -0.9 mirrors a = 0.9).
TEST(KerrObserver, CharacteristicRadiiMatchReference) {
  for (const RadiiRow &row : K_RADII) {
    expectRelative(ko::iscoOffset(row.epsilon, OrbitSense::Prograde), row.xIscoPro, 1e-12,
                   "isco prograde");
    expectRelative(ko::iscoOffset(row.epsilon, OrbitSense::Retrograde), row.xIscoRetro, 1e-12,
                   "isco retrograde");
    expectRelative(ko::marginallyBoundOffset(row.epsilon, OrbitSense::Prograde), row.xMbPro, 1e-12,
                   "marginally bound prograde");
    expectRelative(ko::marginallyBoundOffset(row.epsilon, OrbitSense::Retrograde), row.xMbRetro,
                   1e-12, "marginally bound retrograde");
    expectRelative(ko::photonOrbitOffset(row.epsilon, OrbitSense::Prograde), row.xPhPro, 1e-12,
                   "photon orbit prograde");
    expectRelative(ko::photonOrbitOffset(row.epsilon, OrbitSense::Retrograde), row.xPhRetro, 1e-12,
                   "photon orbit retrograde");
  }
}

// Falsifier: Miller's orbit at the canon spin 1 - a = 1.33e-14 landing off
// r_ISCO - 1 = 3.7611e-5 M or dtau/dt = 1.6286e-5 (61,403x) by more than 1e-6
// relative -- the precision the double-a parameterization cannot reach.
TEST(KerrObserver, CanonMillerOrbitAtExtremalSpin) {
  const double xIsco = ko::iscoOffset(K_CANON_EPSILON, OrbitSense::Prograde);
  expectRelative(xIsco, 3.7611284825013188359e-5, 1e-6, "canon r_ISCO - 1");
  const ko::CircularOrbit miller = ko::circularOrbit(K_CANON_EPSILON, xIsco, OrbitSense::Prograde);
  ASSERT_TRUE(miller.exists);
  expectRelative(miller.properTimeRate, 1.6285857804897317108e-5, 1e-6, "canon dtau/dt");
  EXPECT_NEAR(1.0 / miller.properTimeRate, 61403.0, 1.0);
  // The orbit sits above the marginally bound radius, so it is a bound orbit.
  EXPECT_GT(xIsco, ko::marginallyBoundOffset(K_CANON_EPSILON, OrbitSense::Prograde));
}

// Falsifier: a lapse, frame-drag rate, cylindrical radius, orbital clock, or
// orbital angular velocity off the 50-digit textbook value by more than 1e-12
// relative, or an orbit reported where none is timelike (the r = 3M photon
// sphere at a = 0 among them) or missing where one is.
TEST(KerrObserver, FrameAndOrbitsMatchReference) {
  for (const PointRow &row : K_POINTS) {
    const ko::EquatorialFrame frame = ko::equatorialFrame(row.epsilon, row.x);
    expectRelative(frame.alpha, row.alpha, 1e-12, "alpha");
    expectRelative(frame.omega, row.omega, 1e-12, "omega");
    expectRelative(frame.varpi, row.varpi, 1e-12, "varpi");
    const ko::CircularOrbit pro = ko::circularOrbit(row.epsilon, row.x, OrbitSense::Prograde);
    const ko::CircularOrbit retro = ko::circularOrbit(row.epsilon, row.x, OrbitSense::Retrograde);
    EXPECT_EQ(pro.exists, row.ratePro > 0.0) << "prograde existence at x=" << row.x;
    EXPECT_EQ(retro.exists, row.rateRetro > 0.0) << "retrograde existence at x=" << row.x;
    if (pro.exists) {
      expectRelative(pro.properTimeRate, row.ratePro, 1e-12, "prograde rate");
      expectRelative(pro.angularVelocity, row.omegaPro, 1e-12, "prograde Omega");
    }
    if (retro.exists) {
      expectRelative(retro.properTimeRate, row.rateRetro, 1e-12, "retrograde rate");
      expectRelative(retro.angularVelocity, row.omegaRetro, 1e-12, "retrograde Omega");
    }
  }
}

// Falsifier: the atanh-form delay differing from quadrature of (r^2+a^2)/Delta
// by more than 1e-12 relative, including eps = 0 exactly (h = 0 limit branch)
// and the canon spin where the textbook form divides by r_+ - r_- = 3.3e-7.
TEST(KerrObserver, PrincipalNullDelayMatchesQuadrature) {
  for (const DelayRow &row : K_DELAYS) {
    expectRelative(ko::principalNullDelay(row.epsilon, row.x1, row.x2), row.delayM, 1e-12, "delay");
    EXPECT_EQ(ko::principalNullDelay(row.epsilon, row.x1, row.x2),
              ko::principalNullDelay(row.epsilon, row.x2, row.x1))
        << "delay must be symmetric";
  }
}

// Falsifier: the KerrTimeField built from the canon deficit reporting a delay
// between Miller's orbit and the far bands off quadrature by more than 1e-9
// relative after the cm round trip, or a horizon anywhere but M (1 + h).
TEST(KerrObserver, KerrTimeFieldDelegatesDelayAtCanonSpin) {
  const double massG = 1.0e8 * K_SOLAR_MASS_G;
  const game::KerrTimeField field(massG, game::SpinDeficit{.epsilon = K_CANON_EPSILON});
  const double mCm = field.gravitationalRadiusCm();
  EXPECT_DOUBLE_EQ(field.spinDeficit(), K_CANON_EPSILON);
  expectRelative((field.outerHorizonCm() / mCm) - 1.0, ko::horizonOffset(K_CANON_EPSILON), 1e-6,
                 "horizon offset");
  for (const DelayRow &row : K_DELAYS) {
    if (row.epsilon != K_CANON_EPSILON) {
      continue;
    }
    const double delaySec = field.signalDelaySec(mCm * (1.0 + row.x1), mCm * (1.0 + row.x2));
    expectRelative(delaySec * 2.99792458e10 / mCm, row.delayM, 1e-9, "canon field delay");
  }
}

// Falsifier: the frame-drag rate the field reports in rad/s differing from the
// cm-unit physics::frameDraggingOmega by more than 1e-12 relative -- a unit or
// factor slip in the omega * c / M conversion.
TEST(KerrObserver, FrameDragRateMatchesCgsFormula) {
  const double massG = 6.5e9 * K_SOLAR_MASS_G;
  const game::KerrTimeField field(massG, 0.9);
  const double mCm = field.gravitationalRadiusCm();
  for (const double r : {1.7, 6.0, 20.0, 400.0}) {
    const double expected =
        physics::frameDraggingOmega(r * mCm, 1.5707963267948966, massG, 0.9 * mCm);
    expectRelative(field.frameDragRateRadPerSec(r * mCm), expected, 1e-12, "frame drag");
  }
}

// Falsifier: any ZAMO, static, orbiting, or boosted tetrad failing
// g(e_a, e_b) = eta_ab by more than 1e-12 at (r = 6, a = 0.9) or (r = 3, a = 0).
// r = 3 at a = 0 is the photon sphere, so a generic sub-luminal boost stands in
// for the orbiter there.
TEST(KerrObserver, TetradsAreOrthonormal) {
  const double x6 = 5.0;
  const ko::Tetrad zamo6 = ko::zamoTetrad(0.1, x6);
  EXPECT_LT(orthonormalityError(zamo6), 1e-12);
  EXPECT_LT(orthonormalityError(ko::orbitingTetrad(0.1, x6, OrbitSense::Prograde)), 1e-12);
  EXPECT_LT(orthonormalityError(ko::orbitingTetrad(0.1, x6, OrbitSense::Retrograde)), 1e-12);
  EXPECT_LT(orthonormalityError(ko::boostedTetrad(
                zamo6, ko::Vec3{0.0, 0.0, ko::staticObserverVelocity(zamo6.frame)})),
            1e-12);
  EXPECT_LT(orthonormalityError(ko::boostedTetrad(zamo6, ko::Vec3{0.3, -0.2, 0.4})), 1e-12);

  const ko::Tetrad zamo3 = ko::zamoTetrad(1.0, 2.0);
  EXPECT_LT(orthonormalityError(zamo3), 1e-12);
  EXPECT_FALSE(ko::circularOrbit(1.0, 2.0, OrbitSense::Prograde).exists);
  EXPECT_LT(orthonormalityError(ko::boostedTetrad(zamo3, ko::Vec3{0.3, -0.2, 0.4})), 1e-12);
  // A boost of a boost composes: still orthonormal.
  EXPECT_LT(orthonormalityError(ko::boostedTetrad(ko::boostedTetrad(zamo3, ko::Vec3{0.0, 0.0, 0.6}),
                                                  ko::Vec3{0.5, 0.0, -0.3})),
            1e-12);
}

// Falsifier: the Miller orbiter's tetrad failing orthonormality beyond
// 64 kappa DBL_EPSILON with kappa = 1/alpha^2. The textbook contraction sums
// O(1/alpha^2) terms to O(1), so kappa bounds the roundoff any correct tetrad
// shows; a wrong leg misses by O(1).
TEST(KerrObserver, MillerTetradIsOrthonormalWithinConditioning) {
  const double xIsco = ko::iscoOffset(K_CANON_EPSILON, OrbitSense::Prograde);
  const ko::Tetrad miller = ko::orbitingTetrad(K_CANON_EPSILON, xIsco, OrbitSense::Prograde);
  const double kappa = 1.0 / (miller.frame.alpha * miller.frame.alpha);
  EXPECT_LT(orthonormalityError(miller), 64.0 * kappa * DBL_EPSILON);
  EXPECT_LT(orthonormalityError(ko::zamoTetrad(K_CANON_EPSILON, xIsco)),
            64.0 * kappa * DBL_EPSILON);
}

// Falsifier: the orbiter tetrad's time leg u^t = gamma/alpha disagreeing with
// the BPT closed form 1/(dtau/dt) by more than 1e-12 at (6, 0.9) or 1e-9 at
// Miller (reference rate, whose inverse is 61,403).
TEST(KerrObserver, OrbiterTimeLegIsInverseClockRate) {
  for (const double sense : {1.0, -1.0}) {
    const OrbitSense orbitSense = sense > 0.0 ? OrbitSense::Prograde : OrbitSense::Retrograde;
    const ko::Tetrad orbiter = ko::orbitingTetrad(0.1, 5.0, orbitSense);
    const TextbookOrbit textbook = textbookOrbit(0.9, 6.0, sense);
    expectRelative(ko::legComponents(orbiter, 0).at(0), textbook.timeComponent, 1e-12,
                   "u^t (6, 0.9)");
    const ko::Vec4 u = ko::legComponents(orbiter, 0);
    expectRelative(u.at(3) / u.at(0), textbook.angularVelocity, 1e-12, "Omega from tetrad");
  }
  const double xIsco = ko::iscoOffset(K_CANON_EPSILON, OrbitSense::Prograde);
  const ko::Tetrad miller = ko::orbitingTetrad(K_CANON_EPSILON, xIsco, OrbitSense::Prograde);
  expectRelative(ko::legComponents(miller, 0).at(0), 1.0 / 1.6285857804897317108e-5, 1e-9,
                 "u^t at Miller");
}

// Falsifier: for 1000 lattice directions over the sphere, a photon leaving the orbiter violating
// (E - Omega L) u^t = 1 with u^t and Omega from the BPT closed form (not the
// tetrad) -- 1e-12 at (6, 0.9), 1e-9 at Miller. Outside the ergosphere every
// photon reaches infinity; at Miller (inside it) some backward photons must be
// flagged E <= 0, and g = 1/E must hold wherever E > 0.
TEST(KerrObserver, RedshiftIdentityOverLatticeDirections) {
  const TextbookOrbit outer = textbookOrbit(0.9, 6.0, 1.0);
  const ko::Tetrad orbiter = ko::orbitingTetrad(0.1, 5.0, OrbitSense::Prograde);
  int outerNegative = 0;
  for (int sample = 0; sample < 1000; ++sample) {
    const ko::PhotonConstants photon = ko::photonConstants(orbiter, latticeDirection(sample, 1000));
    if (!photon.positiveEnergy) {
      ++outerNegative;
      continue;
    }
    expectRelative((photon.energy - (outer.angularVelocity * photon.angularMomentum)) *
                       outer.timeComponent,
                   1.0, 1e-12, "(E - Omega L) u^t at (6, 0.9)");
    expectRelative(photon.g, outer.timeComponent * (1.0 - (outer.angularVelocity * photon.lambda)),
                   1e-12, "g = u^t (1 - Omega lambda)");
  }
  EXPECT_EQ(outerNegative, 0);

  const PointRow &canon = K_POINTS.front();
  const ko::Tetrad miller = ko::orbitingTetrad(canon.epsilon, canon.x, OrbitSense::Prograde);
  const double millerUt = 1.0 / canon.ratePro;
  int millerNegative = 0;
  for (int sample = 0; sample < 1000; ++sample) {
    const ko::PhotonConstants photon = ko::photonConstants(miller, latticeDirection(sample, 1000));
    if (!photon.positiveEnergy) {
      ++millerNegative;
      continue;
    }
    expectRelative((photon.energy - (canon.omegaPro * photon.angularMomentum)) * millerUt, 1.0,
                   1e-9, "(E - Omega L) u^t at Miller");
  }
  EXPECT_GT(millerNegative, 0);
  EXPECT_LT(millerNegative, 1000);
}

// Falsifier: a static observer's g = 1/E departing from 1/sqrt(1 - 2/r) for
// any direction -- at a = 0 (static = ZAMO) and at a = 0.9, r = 20 where the
// static observer is a boosted ZAMO and still has u^t = 1/sqrt(-g_tt).
TEST(KerrObserver, StaticObserverRedshiftIsLapse) {
  for (const double epsilon : {1.0, 0.1}) {
    const double r = 20.0;
    const ko::Tetrad zamo = ko::zamoTetrad(epsilon, r - 1.0);
    const ko::Tetrad fixed =
        ko::boostedTetrad(zamo, ko::Vec3{0.0, 0.0, ko::staticObserverVelocity(zamo.frame)});
    for (int sample = 0; sample < 100; ++sample) {
      const ko::PhotonConstants photon = ko::photonConstants(fixed, latticeDirection(sample, 100));
      ASSERT_TRUE(photon.positiveEnergy);
      expectRelative(photon.g, 1.0 / std::sqrt(1.0 - (2.0 / r)), 1e-12, "static g");
    }
  }
}

// Falsifier: at r = 1e8 (flat to 1e-8) an observer moving at v = 0.5 along phi
// seeing a photon at angle theta' from its motion, while the photon constants
// place it at an angle theta in the ZAMO frame with
// cos theta != (cos theta' + v)/(1 + v cos theta'), or at an energy other than
// the Doppler gamma (1 + v cos theta'), by more than 1e-6.
TEST(KerrObserver, SpecialRelativityAberrationFarAway) {
  const double v = 0.5;
  const double gamma = 1.0 / std::sqrt(1.0 - (v * v));
  const ko::Tetrad zamo = ko::zamoTetrad(0.1, 1.0e8 - 1.0);
  const ko::Tetrad mover = ko::boostedTetrad(zamo, ko::Vec3{0.0, 0.0, v});
  const ko::EquatorialFrame &frame = zamo.frame;
  for (const double thetaPrime : {0.0, 0.4, 1.1, 1.5707963267948966, 2.3, 3.0}) {
    const ko::Vec3 direction{std::sin(thetaPrime), 0.0, std::cos(thetaPrime)};
    const ko::PhotonConstants photon = ko::photonConstants(mover, direction);
    ASSERT_TRUE(photon.positiveEnergy);
    const double cosZamo =
        photon.lambda * frame.alpha / (frame.varpi * (1.0 - (frame.omega * photon.lambda)));
    const double expected = (std::cos(thetaPrime) + v) / (1.0 + (v * std::cos(thetaPrime)));
    EXPECT_NEAR(cosZamo, expected, 1e-6) << "theta'=" << thetaPrime;
    EXPECT_NEAR(photon.energy, gamma * (1.0 + (v * std::cos(thetaPrime))), 1e-6)
        << "theta'=" << thetaPrime;
  }
}

namespace {

// A photon leaving the ZAMO at (epsilon, r) along `direction` (r, theta, phi legs).
ko::PhotonConstants zamoPhoton(double epsilon, double r, const ko::Vec3 &direction) {
  return ko::photonConstants(ko::zamoTetrad(epsilon, r - 1.0), direction);
}

constexpr ko::Vec3 K_OUTWARD{1.0, 0.0, 0.0};
constexpr ko::Vec3 K_INWARD{-1.0, 0.0, 0.0};
constexpr ko::Vec3 K_FORWARD{0.0, 0.0, 1.0};  // tangential, +phi
constexpr ko::Vec3 K_BACKWARD{0.0, 0.0, -1.0}; // tangential, -phi

} // namespace

// Falsifier: a Schwarzschild tangential photon at 2.5M (impact parameter
// 2.5 / sqrt(0.2) = 5.59M, above the critical 3 sqrt(3) M = 5.196M, but inside
// the 3M photon sphere, so at an apoapsis under the barrier) reported as
// reaching infinity in either direction -- the E > 0 rule said it did -- or
// radial photons there misjudged: outward escapes but came from the horizon.
TEST(KerrObserver, InsidePhotonSphereTangentialPhotonIsTrapped) {
  const ko::PhotonConstants tangential = zamoPhoton(1.0, 2.5, K_FORWARD);
  EXPECT_TRUE(tangential.positiveEnergy);
  EXPECT_NEAR(tangential.lambda, 2.5 / std::sqrt(0.2), 1e-12);
  EXPECT_FALSE(tangential.escapesToInfinity);
  EXPECT_FALSE(tangential.fromInfinity);

  const ko::PhotonConstants outward = zamoPhoton(1.0, 2.5, K_OUTWARD);
  EXPECT_TRUE(outward.escapesToInfinity);
  EXPECT_FALSE(outward.fromInfinity);
  const ko::PhotonConstants inward = zamoPhoton(1.0, 2.5, K_INWARD);
  EXPECT_FALSE(inward.escapesToInfinity);
  EXPECT_TRUE(inward.fromInfinity);
}

// Falsifier: outside the photon sphere at 4M a tangential photon (b = 5.657M
// > b_c) sits at a periapsis and must connect to infinity both ways; a radial
// photon (b = 0 < b_c) crosses no barrier, so inward came from infinity and
// falls in, outward escapes and came from the horizon; a photon aimed 30
// degrees inward of tangential with b = 4.90M < b_c falls in forward.
TEST(KerrObserver, OutsidePhotonSphereConnectivity) {
  const ko::PhotonConstants tangential = zamoPhoton(1.0, 4.0, K_FORWARD);
  EXPECT_TRUE(tangential.escapesToInfinity);
  EXPECT_TRUE(tangential.fromInfinity);
  const ko::PhotonConstants inward = zamoPhoton(1.0, 4.0, K_INWARD);
  EXPECT_FALSE(inward.escapesToInfinity);
  EXPECT_TRUE(inward.fromInfinity);
  const ko::PhotonConstants outward = zamoPhoton(1.0, 4.0, K_OUTWARD);
  EXPECT_TRUE(outward.escapesToInfinity);
  EXPECT_FALSE(outward.fromInfinity);
  // b = 4 cos(30 deg) / sqrt(1 - 2/4) = 4.899M: below b_c, so no barrier.
  const double angle = std::numbers::pi / 6.0;
  const ko::PhotonConstants steep = zamoPhoton(1.0, 4.0, {-std::sin(angle), 0.0, std::cos(angle)});
  EXPECT_NEAR(steep.lambda, 4.0 * std::cos(angle) / std::sqrt(0.5), 1e-12);
  EXPECT_FALSE(steep.escapesToInfinity);
  EXPECT_TRUE(steep.fromInfinity);
  // Same angle outward of tangential at 2.5M, inside the photon sphere, with
  // b = 4.84M < b_c: no barrier, so it escapes forward.
  const ko::PhotonConstants climbing =
      zamoPhoton(1.0, 2.5, {std::sin(angle), 0.0, std::cos(angle)});
  EXPECT_TRUE(climbing.escapesToInfinity);
}

// Falsifier: at r = 3M around a = 0.9, between the prograde photon shell
// (1.558M) and the retrograde one (3.910M), a tangential photon along the
// hole's rotation failing to reach infinity (it is outside its shell: a
// periapsis) or one against the rotation reaching it (inside its shell: an
// apoapsis under the barrier).
TEST(KerrObserver, KerrShellsSplitProgradeFromRetrograde) {
  const ko::PhotonConstants prograde = zamoPhoton(0.1, 3.0, K_FORWARD);
  EXPECT_TRUE(prograde.escapesToInfinity);
  EXPECT_TRUE(prograde.fromInfinity);
  const ko::PhotonConstants retrograde = zamoPhoton(0.1, 3.0, K_BACKWARD);
  EXPECT_FALSE(retrograde.escapesToInfinity);
  EXPECT_FALSE(retrograde.fromInfinity);
  // Outside both shells, at 5M, both tangential photons connect.
  EXPECT_TRUE(zamoPhoton(0.1, 5.0, K_BACKWARD).escapesToInfinity);
  EXPECT_TRUE(zamoPhoton(0.1, 5.0, K_FORWARD).fromInfinity);
}

// Falsifier: around a = -0.9 (epsilon = 1.9) a prograde orbit -- one that
// co-rotates with the hole, toward -phi -- differing from the mirror of the
// a = 0.9 prograde orbit in radius or clock, or sharing its +phi direction:
// Omega and the ZAMO-frame speed must flip sign, and the orbiter's tetrad
// must satisfy u^phi / u^t = Omega and stay orthonormal in the a = -0.9 metric.
TEST(KerrObserver, NegativeSpinProgradeMirrorsPositiveSpin) {
  for (const OrbitSense sense : {OrbitSense::Prograde, OrbitSense::Retrograde}) {
    // 2 - 1.9 rounds 1e-16 away from 0.1, so the mirror agrees to rounding.
    expectRelative(ko::iscoOffset(1.9, sense), ko::iscoOffset(0.1, sense), 1e-12, "isco");
    expectRelative(ko::marginallyBoundOffset(1.9, sense), ko::marginallyBoundOffset(0.1, sense),
                   1e-12, "marginally bound");
    const ko::CircularOrbit mirrored = ko::circularOrbit(1.9, 5.0, sense);
    const ko::CircularOrbit direct = ko::circularOrbit(0.1, 5.0, sense);
    ASSERT_TRUE(mirrored.exists);
    expectRelative(mirrored.properTimeRate, direct.properTimeRate, 1e-12, "mirrored clock");
    expectRelative(mirrored.angularVelocity, -direct.angularVelocity, 1e-12, "mirrored Omega");
    expectRelative(mirrored.zamoVelocity, -direct.zamoVelocity, 1e-12, "mirrored ZAMO speed");
    const ko::Tetrad orbiter = ko::orbitingTetrad(1.9, 5.0, sense);
    const ko::Vec4 u = ko::legComponents(orbiter, 0);
    expectRelative(u.at(3) / u.at(0), mirrored.angularVelocity, 1e-12, "tetrad Omega");
    EXPECT_LT(orthonormalityError(orbiter), 1e-12);
  }
  EXPECT_LT(ko::circularOrbit(1.9, 5.0, OrbitSense::Prograde).angularVelocity, 0.0);
  EXPECT_LT(ko::equatorialFrame(1.9, 5.0).omega, 0.0); // frame dragging toward -phi
}

namespace {

// Schwarzschild ZAMO at 6M sending a photon outward (or inward) in the
// equatorial plane with impact parameter `b`: cos(angle) = b sqrt(1 - 2/6) / 6.
ko::PhotonConstants sixMPhoton(double b, double radialSign) {
  const double cosine = b * std::sqrt(1.0 - (2.0 / 6.0)) / 6.0;
  const double sine = std::sqrt(1.0 - (cosine * cosine));
  return zamoPhoton(1.0, 6.0, {radialSign * sine, 0.0, cosine});
}

} // namespace

// Falsifier: a ray with exactly the critical impact parameter b_c = 3 sqrt(3) M
// -- a double zero of R at the 3M photon sphere -- reported as bouncing off
// it: heading inward it spirals onto the photon sphere, so it neither
// escapes (moving inward) nor came from infinity (moving outward, traced
// back). At b_c (1 + 1e-9) the barrier is a genuine turning point and the ray
// connects both ways; at b_c (1 - 1e-9) there is no barrier and the inward
// leg falls into the hole.
TEST(KerrObserver, SeparatrixRaysAsymptoteToThePhotonSphere) {
  const double critical = 3.0 * std::numbers::sqrt3;
  // Codex's case: (1/sqrt 2, 0, 1/sqrt 2) at 6M carries lambda = 3 sqrt 3.
  const ko::PhotonConstants exact =
      zamoPhoton(1.0, 6.0, {std::numbers::sqrt2 / 2.0, 0.0, std::numbers::sqrt2 / 2.0});
  EXPECT_NEAR(exact.lambda, critical, 1e-12);
  EXPECT_TRUE(exact.escapesToInfinity);
  EXPECT_FALSE(exact.fromInfinity);
  const ko::PhotonConstants exactInward = sixMPhoton(critical, -1.0);
  EXPECT_FALSE(exactInward.escapesToInfinity);
  EXPECT_TRUE(exactInward.fromInfinity);

  const ko::PhotonConstants above = sixMPhoton(critical * (1.0 + 1e-9), 1.0);
  EXPECT_TRUE(above.escapesToInfinity);
  EXPECT_TRUE(above.fromInfinity);
  const ko::PhotonConstants aboveInward = sixMPhoton(critical * (1.0 + 1e-9), -1.0);
  EXPECT_TRUE(aboveInward.escapesToInfinity);
  EXPECT_TRUE(aboveInward.fromInfinity);

  const ko::PhotonConstants below = sixMPhoton(critical * (1.0 - 1e-9), 1.0);
  EXPECT_TRUE(below.escapesToInfinity);
  EXPECT_FALSE(below.fromInfinity);
  const ko::PhotonConstants belowInward = sixMPhoton(critical * (1.0 - 1e-9), -1.0);
  EXPECT_FALSE(belowInward.escapesToInfinity);
  EXPECT_TRUE(belowInward.fromInfinity);
}

// Falsifier: the prograde ISCO offset for a deficit far below the canon
// spin departing from its asymptote x = 2u (1 + 7u/4), u = (epsilon/2)^{1/3}
// (from y^3 (y + 4) = 2 epsilon (1 + 4y) + 3 epsilon^2; next term O(u^2),
// below 1e-20 here), by more than 1e-12 relative, or epsilon = 0 giving
// anything but r_isco = M -- a solver that stops contracting from a fixed
// start before it reaches the root (it returned 1.8e-70 for 1e-300).
TEST(KerrObserver, IscoConvergesForUltraExtremalDeficits) {
  for (const double epsilon : {1e-30, 1e-100, 1e-200, 1e-300}) {
    const double u = std::cbrt(epsilon / 2.0);
    expectRelative(ko::iscoOffset(epsilon, OrbitSense::Prograde), 2.0 * u * (1.0 + (1.75 * u)),
                   1e-12, "ultra-extremal isco");
  }
  EXPECT_EQ(ko::iscoOffset(0.0, OrbitSense::Prograde), 0.0);
  expectRelative(ko::iscoOffset(0.0, OrbitSense::Retrograde), 8.0, 1e-15, "extremal retrograde");
}
