#!/usr/bin/env python3
"""Reference values of Carlson's symmetric elliptic integrals R_F, R_D, R_J, R_C.

mpmath's elliprf, elliprd, elliprj and elliprc are evaluated at 40 significant
digits and confirmed at 60. Inputs are written as C++ hexadecimal floating
literals, so the C++ test reads the exact doubles mpmath used; outputs carry
25 significant digits.

Row groups:
  gen    - log-uniform (x, y, z, p) on [1e-3, 1e3]
  Kk     - complete-integral arguments (0, 1 - k^2, 1, 1 - n), k up to 0.999999
  inc    - incomplete-integral arguments (cos^2 phi, 1 - k^2 sin^2 phi, 1, 1 - n sin^2 phi)
  near   - nearly equal arguments, the case duplication converges to
  zero   - one of x, y zero with widely spread partners
R_C rows cover x < y, x > y, x = y, x = 0 and nearly equal arguments.

Usage: $PYTHON scripts/gen_carlson_reference.py > tests/carlson_reference.inc
"""

from __future__ import annotations

import argparse
import math
import random
from collections.abc import Callable

import mpmath as mp

WORK_DPS = 40
CHECK_DPS = 60

Quad = tuple[str, float, float, float, float]


def build_quads() -> list[Quad]:
    rng = random.Random(20260925)
    rows: list[Quad] = []

    def lu() -> float:
        return 10.0 ** rng.uniform(-3.0, 3.0)

    for _ in range(60):
        rows.append(("gen", lu(), lu(), lu(), lu()))
    for k in (0.1, 0.5, 0.9, 0.99, 0.9999, 0.999999):
        for n in (0.1, 0.5, 0.9):
            rows.append(("Kk", 0.0, 1.0 - k * k, 1.0, 1.0 - n))
    for _ in range(30):
        phi = rng.uniform(0.01, 1.55)
        k = rng.uniform(0.0, 0.9999)
        n = rng.uniform(0.0, 0.95)
        s, c = math.sin(phi), math.cos(phi)
        rows.append(("inc", c * c, 1.0 - k * k * s * s, 1.0, 1.0 - n * s * s))
    for delta in (1.0e-12, 1.0e-8, 1.0e-4, 1.0e-2):
        for y in (0.37, 250.0):
            rows.append(("near", y * (1.0 + delta), y, y * (1.0 + 2.0 * delta), y * (1.0 - delta)))
    rows.append(("zero", 0.0, 1.0e-3, 1.0e3, 1.0))
    rows.append(("zero", 0.0, 1.0e3, 1.0e-3, 1.0e-2))
    rows.append(("zero", 5.0, 0.0, 2.0, 7.0))
    rows.append(("zero", 1.0e-3, 0.0, 1.0e3, 0.5))
    return rows


RC_ROWS: list[tuple[float, float]] = [
    (1.0, 2.0),
    (1.0, 1.0 + 1.0e-10),
    (1.0e-8, 1.0),
    (0.0, 3.0),
    (2.0, 1.0),
    (1.0 + 1.0e-10, 1.0),
    (1.0e8, 1.0),
    (4.0, 4.0),
    (1.0e-3, 1.0e3),
    (9.0, 9.0 * (1.0 - 1.0e-6)),
    (0.25, 0.2500000001),
]


def quad_values(x: float, y: float, z: float, p: float) -> list:
    xs, ys, zs, ps = (mp.mpf(v) for v in (x, y, z, p))
    return [mp.elliprf(xs, ys, zs), mp.elliprd(xs, ys, zs), mp.elliprj(xs, ys, zs, ps)]


def confirmed(fn: Callable[..., list], *args: float) -> list:
    """fn(*args) at WORK_DPS after agreeing with CHECK_DPS to 1e-35 relative."""
    mp.mp.dps = CHECK_DPS
    check = fn(*args)
    mp.mp.dps = WORK_DPS
    work = fn(*args)
    for a, b in zip(work, check, strict=True):
        if abs(a - b) > mp.mpf("1e-35") * abs(b):
            raise SystemExit(f"referee disagrees with itself at {WORK_DPS} vs {CHECK_DPS} digits")
    return work


def num(v: mp.mpf) -> str:
    return mp.nstr(v, 25, strip_zeros=False)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.parse_args()
    print("// Generated by scripts/gen_carlson_reference.py; do not edit by hand.")
    print(f"// mpmath {mp.__version__}, {WORK_DPS} digits, confirmed at {CHECK_DPS} digits.")
    print("// {group, x, y, z, p, R_F(x,y,z), R_D(x,y,z), R_J(x,y,z,p)}")
    print("constexpr CarlsonRow CARLSON_ROWS[] = {")
    for group, x, y, z, p in build_quads():
        rf, rd, rj = confirmed(quad_values, x, y, z, p)
        args = ", ".join(v.hex() for v in (x, y, z, p))
        print(f'    {{"{group}", {args},')
        print(f"     {num(rf)}, {num(rd)}, {num(rj)}}},")
    print("};")
    print("// {x, y, R_C(x,y)}")
    print("constexpr CarlsonRcRow CARLSON_RC_ROWS[] = {")
    for x, y in RC_ROWS:
        (rc,) = confirmed(lambda a, b: [mp.elliprc(mp.mpf(a), mp.mpf(b))], x, y)
        print(f"    {{{x.hex()}, {y.hex()}, {num(rc)}}},")
    print("};")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
