#!/usr/bin/env python3
"""Reference values of the modified Bessel function K_nu and its tail integral.

Each row holds nu, x, the exponentially scaled e^x K_nu(x), and the scaled
tail integral e^x * integral_x^inf K_nu(t) dt. The orders are the ones the
physics headers use: 0, 1, and 2 for the thermal Maxwell-Juttner and Faraday
coefficients, and 1/3, 2/3, and 5/3 for the synchrotron functions
F(x) = x * integral_x^inf K_{5/3} and G(x) = x K_{2/3}(x).

Each row is the exact function at the binary64 order and argument the C++
test passes in: nu is the double nearest 1/3, 2/3, or 5/3 (the value the
C++ expression 1.0 / 3.0 produces), and x is written as a hex float. The
x grid spans 1e-4 to 1e5 at eight points per decade, plus the synchrotron
lookup table's domain ends and one-sided samples around x = 0.01 and x = 10.

e^x K_nu comes from mpmath's besselk. The tail comes from tanh-sinh
quadrature of int_0^S e^{-x (cosh s - 1)} cosh(nu s) / cosh(s) ds, where S
is the point past which the integrand bound e^{-x (cosh s - 1) + nu s}
falls below 10^-(dps + 10). Both columns are recomputed at a higher
precision and must agree to 1e-30.

Usage: $PYTHON scripts/gen_bessel_k_reference.py > tests/bessel_k_reference.inc
"""

from __future__ import annotations

import argparse
from concurrent.futures import ProcessPoolExecutor

import mpmath as mp

WORK_DPS = 50
CHECK_DPS = 70

# (C++ spelling, binary64 value)
ORDERS: list[tuple[str, float]] = [
    ("0.0", 0.0),
    ("1.0", 1.0),
    ("2.0", 2.0),
    ("1.0 / 3.0", 1.0 / 3.0),
    ("2.0 / 3.0", 2.0 / 3.0),
    ("5.0 / 3.0", 5.0 / 3.0),
]

X_VALUES: list[float] = sorted(
    {float(10.0 ** (k / 8.0)) for k in range(-32, 41)}
    | {0.001, 0.0099, 0.0101, 9.9, 10.1, 10.92, 30.0}
)


def scaled_k(nu: mp.mpf, x: mp.mpf) -> mp.mpf:
    return mp.exp(x) * mp.besselk(nu, x)


def truncation(nu: mp.mpf, x: mp.mpf) -> mp.mpf:
    """Return S with x (cosh S - 1) - nu S >= (dps + 10) ln 10, to bisection accuracy."""
    target = (mp.mp.dps + 10) * mp.log(10)

    def exponent(s: mp.mpf) -> mp.mpf:
        return x * (mp.cosh(s) - 1) - nu * s

    hi = mp.mpf(1)
    while exponent(hi) < target:
        hi *= 2
    lo = mp.mpf(0)
    for _ in range(200):
        mid = (lo + hi) / 2
        if exponent(mid) < target:
            lo = mid
        else:
            hi = mid
    return hi


def scaled_tail(nu: mp.mpf, x: mp.mpf) -> mp.mpf:
    # e^x * int_x^inf K_nu(t) dt = int_0^inf e^{-x (cosh s - 1)} cosh(nu s) / cosh(s) ds
    # (DLMF 10.32.9 integrated over x), which stays finite as x grows.
    def integrand(s: mp.mpf) -> mp.mpf:
        return mp.exp(-x * (mp.cosh(s) - 1)) * mp.cosh(nu * s) / mp.cosh(s)

    upper = truncation(nu, x)
    # The integrand's width is about sqrt(2 / x) for large x; split there and
    # at equal fractions of the range so every tanh-sinh segment is smooth.
    width = min(upper, mp.sqrt(2 / x))
    points = sorted(
        {mp.mpf(0), width / 4, width / 2, width, *(upper * i / 16 for i in range(1, 17))}
    )
    return mp.quad(integrand, points)


def row(nu: float, x: float) -> tuple[mp.mpf, mp.mpf]:
    return scaled_k(mp.mpf(nu), mp.mpf(x)), scaled_tail(mp.mpf(nu), mp.mpf(x))


def order_rows(label: str, nu: float) -> list[str]:
    lines = []
    for x in X_VALUES:
        mp.mp.dps = CHECK_DPS
        k_check, tail_check = row(nu, x)
        mp.mp.dps = WORK_DPS
        k, tail = row(nu, x)
        for got, check in ((k, k_check), (tail, tail_check)):
            if abs(got - check) > mp.mpf("1e-30") * abs(check):
                raise SystemExit(f"referee disagrees with itself at nu={label}, x={x}")
        lines.append(
            f"    {{{label}, {x.hex()}, {mp.nstr(k, 25, strip_zeros=False)}, "
            f"{mp.nstr(tail, 25, strip_zeros=False)}}},"
        )
    return lines


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.parse_args()
    labels, values = zip(*ORDERS, strict=True)
    with ProcessPoolExecutor(max_workers=len(ORDERS)) as pool:
        blocks = list(pool.map(order_rows, labels, values))
    print("// Generated by scripts/gen_bessel_k_reference.py; do not edit by hand.")
    print("// NOLINTBEGIN(modernize-use-designated-initializers): columns named below")
    print(f"// mpmath {mp.__version__}, {WORK_DPS} digits, confirmed at {CHECK_DPS} digits.")
    print("// {nu, x, e^x K_nu(x), e^x * integral_x^inf K_nu(t) dt}")
    print("constexpr BesselKRow BESSEL_K_ROWS[] = {")
    for block in blocks:
        print("\n".join(block))
    print("};")
    print("// NOLINTEND(modernize-use-designated-initializers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
