#!/usr/bin/env python3
"""Reference values for tests/kerr_observer_test.cpp from textbook Kerr formulas.

Every quantity is evaluated at 50 significant digits from the Boyer-Lindquist
spin a and radius r (G = c = M = 1), not from the spin-deficit algebra that
src/physics/kerr_observer.h uses, so the table is an independent referee:

- ZAMO lapse, frame-drag rate, and cylindrical radius from the equatorial
  metric (Bardeen, Press & Teukolsky 1972, eqs. 2.2-2.4).
- Circular-orbit dtau/dt and Omega from BPT 1972 eq. 2.16 with a -> -a for
  the retrograde sense.
- ISCO from the BPT 1972 closed form (eq. 2.21), marginally bound radius
  2 -+ a + 2 sqrt(1 -+ a), photon orbit 2 (1 + cos(2/3 acos(-+a))).
- Principal-null coordinate delay by adaptive quadrature of
  (r^2 + a^2) / Delta.

Usage: $PYTHON scripts/gen_kerr_observer_reference.py
The output is the C++ reference block embedded verbatim in the test between
its clang-format markers; rerun and diff to audit it.
"""

import mpmath
from mpmath import acos, cbrt, cos, mp, mpf, quad, sqrt

mp.dps = 50

# Spin deficits eps = 1 - a. 1.33e-14 is the Gargantua spin that puts
# Miller's planet at 1 h = 7 yr on the prograde ISCO; 1.9 is a = -0.9.
DEFICITS = ["1.33e-14", "1e-8", "1e-4", "0.002", "0.1", "0.4", "1.0", "1.9"]


def spin(eps: str) -> mpf:
    return 1 - mpf(eps)


def isco(a: mpf, sense: int) -> mpf:
    """BPT eq. 2.21 is even in a with the sense taken against the hole's
    rotation; a signed a flips which branch co-rotates with +phi."""
    spin_sign = 1 if a >= 0 else -1
    a = abs(a)
    z1 = 1 + cbrt(1 - a * a) * (cbrt(1 + a) + cbrt(1 - a))
    z2 = sqrt(3 * a * a + z1 * z1)
    root = sqrt((3 - z1) * (3 + z1 + 2 * z2))
    return 3 + z2 - sense * spin_sign * root


def marginally_bound(a: mpf, sense: int) -> mpf:
    return 2 - sense * a + 2 * sqrt(1 - sense * a)


def photon_orbit(a: mpf, sense: int) -> mpf:
    return 2 * (1 + cos(mpf(2) / 3 * acos(-sense * a)))


def zamo(a: mpf, r: mpf) -> tuple[mpf, mpf, mpf]:
    delta = r * r - 2 * r + a * a
    big_a = (r * r + a * a) ** 2 - a * a * delta
    alpha = sqrt(r * r * delta / big_a)
    omega = 2 * a * r / big_a
    varpi = sqrt(big_a) / r
    return alpha, omega, varpi


def orbit(a: mpf, r: mpf, sense: int) -> tuple[mpf, mpf]:
    """(dtau/dt, Omega) for a circular equatorial geodesic, or (-1, 0) when none exists."""
    rm32 = r ** mpf("-1.5")
    radicand = 1 - 3 / r + sense * 2 * a * rm32
    if radicand <= 0:
        return mpf(-1), mpf(0)
    rate = sqrt(radicand) / (1 + sense * a * rm32)
    omega = sense / (r ** mpf("1.5") + sense * a)
    return rate, omega


def delay(a: mpf, r1: mpf, r2: mpf) -> mpf:
    def integrand(r: mpf) -> mpf:
        return (r * r + a * a) / (r * r - 2 * r + a * a)

    # Geometric breakpoints keep the quadrature resolved near the inner end.
    points = [r1]
    step = r1 - 1
    while 1 + 4 * step < r2:
        step *= 4
        points.append(1 + step)
    points.append(r2)
    value, error = quad(integrand, points, error=True)
    if error > mpf(10) ** (-30) * abs(value):
        raise RuntimeError(f"quadrature error {error} too large")
    return value


def emit(value: mpf, digits: int = 20) -> str:
    return mpmath.nstr(value, digits, min_fixed=-1, max_fixed=-1)


# Literals clang-tidy's modernize-use-std-numbers would ask to spell as a
# std::numbers constant; a reference value that happens to equal one keeps its
# digits and carries a NOLINT naming why.
NAMED_CONSTANTS = [sqrt(2), sqrt(3), 1 / sqrt(3), 1 / sqrt(2), mpmath.pi, mpmath.e]


def row(fields: list[tuple[str, str]]) -> str:
    body = ", ".join(f".{name} = {text}" for name, text in fields)
    line = "    {" + body + "},"
    collides = any(
        abs(mpf(text) - constant) < mpf(10) ** -15
        for _, text in fields
        for constant in NAMED_CONSTANTS
    )
    if collides:
        line += " // NOLINT(modernize-use-std-numbers) -- generated reference value"
    return line


def main() -> None:
    print("// clang-format off")
    print(
        f"// Generated by $PYTHON scripts/gen_kerr_observer_reference.py"
        f" (mpmath {mpmath.__version__}, mp.dps = {mp.dps})."
    )
    print(f"constexpr std::array<RadiiRow, {len(DEFICITS)}> K_RADII{{{{")
    for eps in DEFICITS:
        a = spin(eps)
        values = [
            ("xIscoPro", isco(a, 1) - 1),
            ("xIscoRetro", isco(a, -1) - 1),
            ("xMbPro", marginally_bound(a, 1) - 1),
            ("xMbRetro", marginally_bound(a, -1) - 1),
            ("xPhPro", photon_orbit(a, 1) - 1),
            ("xPhRetro", photon_orbit(a, -1) - 1),
        ]
        print(row([("epsilon", eps)] + [(name, emit(v)) for name, v in values]))
    print("}};")

    a_canon = spin("1.33e-14")
    x_miller = isco(a_canon, 1) - 1
    points = [
        ("1.33e-14", x_miller),
        ("0.1", mpf(5)),
        ("0.1", mpf("0.7")),
        ("0.1", mpf(19)),
        ("1.0", mpf(2)),
        ("1.0", mpf(5)),
        ("0.002", mpf("0.5")),
        ("1.9", mpf(9)),
    ]
    print("// A rate of -1 marks a sense with no timelike circular orbit at that radius.")
    print(f"constexpr std::array<PointRow, {len(points)}> K_POINTS{{{{")
    for eps, x in points:
        a = spin(eps)
        r = 1 + x
        alpha, omega, varpi = zamo(a, r)
        rate_pro, omega_pro = orbit(a, r, 1)
        rate_retro, omega_retro = orbit(a, r, -1)
        values = [
            ("x", x),
            ("alpha", alpha),
            ("omega", omega),
            ("varpi", varpi),
            ("ratePro", rate_pro),
            ("omegaPro", omega_pro),
            ("rateRetro", rate_retro),
            ("omegaRetro", omega_retro),
        ]
        print(row([("epsilon", eps)] + [(name, emit(v)) for name, v in values]))
    print("}};")

    delays = [
        ("0.1", mpf("0.7"), mpf(399)),
        ("0.1", mpf(5), mpf(19)),
        ("1.0", mpf(2), mpf(199)),
        ("0.002", mpf("0.1"), mpf(99)),
        ("1e-8", mpf("0.01"), mpf(49)),
        ("1.33e-14", x_miller, mpf(9)),
        ("1.33e-14", x_miller, mpf(399)),
        ("0.0", mpf("0.5"), mpf(10)),
    ]
    print(f"constexpr std::array<DelayRow, {len(delays)}> K_DELAYS{{{{")
    for eps, x1, x2 in delays:
        a = spin(eps)
        value = delay(a, 1 + x1, 1 + x2)
        fields = [("epsilon", eps), ("x1", emit(x1)), ("x2", emit(x2)), ("delayM", emit(value))]
        print(row(fields))
    print("}};")
    print("// clang-format on")


if __name__ == "__main__":
    main()
