#!/usr/bin/env python3
"""Reference Lyapunov exponents of bound Kerr photon orbits (G = c = M = 1).

gamma is evaluated from its definition rather than from the closed form of
src/physics/photon_ring.h:

    gamma = sqrt(R''(r) / 2) * integral_{theta_-}^{theta_+} dtheta / sqrt(Theta(theta)),

with R(r) = (r^2 + a^2 - a lambda)^2 - Delta (eta + (lambda - a)^2) differentiated
numerically, Theta(theta) = eta + a^2 cos^2 theta - lambda^2 cot^2 theta
integrated by tanh-sinh quadrature between its turning points, and lambda, eta
the critical values of the orbit at r. Each row confirms R(r) = R'(r) = 0 and
agrees with itself at 60 and 80 digits to 1e-25.

Usage: $PYTHON scripts/gen_photon_ring_reference.py > tests/photon_ring_reference.inc
"""

from __future__ import annotations

import argparse

import mpmath as mp

# The 1/sqrt(Theta) endpoint singularity turns a rounding error eps in the
# turning point into an eps^(1/2) error of the integral, so the working
# precision is twice the 25 digits written out.
WORK_DPS = 60
CHECK_DPS = 80

# (spin, fraction of the way from r_+ to r_- across the photon shell)
ROWS: list[tuple[float, float]] = [
    (1.0e-3, 0.5),
    (0.5, 0.1),
    (0.5, 0.5),
    (0.5, 0.9),
    (0.9, 0.05),
    (0.9, 0.5),
    (0.9, 0.95),
    (0.99, 0.3),
    (0.99, 0.7),
]


def shell(a: mp.mpf) -> tuple[mp.mpf, mp.mpf]:
    r_plus = 2 * (1 + mp.cos(mp.mpf(2) / 3 * mp.acos(-a)))
    r_minus = 2 * (1 + mp.cos(mp.mpf(2) / 3 * mp.acos(a)))
    return r_plus, r_minus


def gamma(a: mp.mpf, r: mp.mpf) -> mp.mpf:
    delta = r * r - 2 * r + a * a
    lam = a + r * (r - 2 * delta / (r - 1)) / a
    eta = r**3 * (4 * delta / (r - 1) ** 2 - r) / (a * a)

    def radial(x: mp.mpf) -> mp.mpf:
        dx = x * x - 2 * x + a * a
        return (x * x + a * a - a * lam) ** 2 - dx * (eta + (lam - a) ** 2)

    scale = r**4
    if abs(radial(r)) > mp.mpf(10) ** (-mp.mp.dps + 8) * scale:
        raise SystemExit("R(r) != 0 on the photon orbit")
    if abs(mp.diff(radial, r)) > mp.mpf(10) ** (-mp.mp.dps + 8) * scale:
        raise SystemExit("R'(r) != 0 on the photon orbit")

    # Theta vanishes where v = cos^2 theta solves -a^2 v^2 + (a^2 - eta - lam^2) v + eta = 0.
    roots = mp.polyroots([-a * a, a * a - eta - lam * lam, eta], extraprec=2 * mp.mp.dps)
    v_plus = max(mp.re(v) for v in roots)
    theta_minus = mp.acos(mp.sqrt(v_plus))
    theta_plus = mp.pi - theta_minus

    def polar(th: mp.mpf) -> mp.mpf:
        c = mp.cos(th)
        return eta + a * a * c * c - lam * lam * c * c / (1 - c * c)

    libration = mp.quad(lambda th: 1 / mp.sqrt(polar(th)), [theta_minus, mp.pi / 2, theta_plus])
    value = mp.sqrt(mp.diff(radial, r, 2) / 2) * libration
    if abs(mp.im(value)) > mp.mpf("1e-25") * abs(value):
        raise SystemExit("complex libration integral: turning point not resolved")
    return mp.re(value)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.parse_args()
    print("// Generated by scripts/gen_photon_ring_reference.py; do not edit by hand.")
    print(f"// mpmath {mp.__version__}, {WORK_DPS} digits, confirmed at {CHECK_DPS} digits.")
    print("// {a, r, gamma}")
    for spin, frac in ROWS:
        mp.mp.dps = WORK_DPS
        a = mp.mpf(spin)
        r_plus, r_minus = shell(a)
        r = float(r_plus + mp.mpf(frac) * (r_minus - r_plus))
        value = gamma(a, mp.mpf(r))
        mp.mp.dps = CHECK_DPS
        check = gamma(mp.mpf(spin), mp.mpf(r))
        if abs(value - check) > mp.mpf("1e-25") * abs(check):
            raise SystemExit(f"referee disagrees with itself at {WORK_DPS} vs {CHECK_DPS} digits")
        mp.mp.dps = WORK_DPS
        print(f"{{{spin.hex()}, {r.hex()}, {mp.nstr(value, 25, strip_zeros=False)}}},")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
